using Common.Common;
using Medical.Office.App.Dtos.Prescription;

namespace Medical.Office.App.UseCases.Prescription.PatientLaboratoryAndImagingRequests.Update.Responses;

public record PatientLaboratoryAndImagingRequestsUpdateSuccess(PatientLaboratoryAndImagingRequestsDto PatientLaboratoryAndImaging) : PatientLaboratoryAndImagingRequestsUpdateResponse, ISuccess;