name: Build Inno Setup Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile Inno Setup installer
        run: |
          docker run --rm -v "${{ github.workspace }}:/work" amake/innosetup installer.iss

      - name: Find and rename .exe
        run: |
          EXE_PATH=$(find . -name "*.exe" | head -n 1)
          echo "Found installer at $EXE_PATH"
          cp "$EXE_PATH" ./MedicalSoftInstaller.exe

      - name: Upload installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MedicalSoftInstaller
          path: MedicalSoftInstaller.exe
