name: Build Installers for Windows and Linux

on:
  push:
    tags:
      - 'v*.*.*'  # Ejemplo: v1.0.0
  workflow_dispatch:

jobs:
  build-installers:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------- WINDOWS INSTALLER ----------------
      - name: Set up Inno Setup
        run: choco install innosetup --no-progress

      - name: Compile Inno Setup installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "Windows\installer.iss"

      # ---------------- LINUX-OSX INSTALLER ----------------
      - name: Prepare Linux/macOS installer
        shell: pwsh
        run: |
          $outDir = "LinuxOutput"
          New-Item -ItemType Directory -Path $outDir -Force
          Copy-Item Linux-OSX/install.sh, Linux-OSX/docker-compose.yml, InstallerSource/nginx.conf -Destination $outDir -Recurse
          icacls "$outDir/install.sh" /grant Everyone:RX > $null
          Compress-Archive -Path "$outDir/*" -DestinationPath "$outDir/installer-linux-macos.zip" -Force


      # ---------------- UPLOAD RELEASE ----------------
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Windows/Output/*.exe
            LinuxOutput/installer-linux-macos.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
