name: Build Inno Setup Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker (amake/innosetup)
        run: |
          docker run --rm -v "${{ github.workspace }}:/work" amake/innosetup installer.iss

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v3
        with:
          name: MedicalSoftInstaller
          path: Output/MedicalSoftInstaller.exe
