name: Build Installers for Windows and Linux

on:
  push:
    tags:
      - 'v*.*.*'  # Ejemplo: v1.0.0
  workflow_dispatch:

jobs:
  build-installers:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------- WINDOWS INSTALLER ----------------
      - name: Set up Inno Setup
        run: choco install innosetup --no-progress

      - name: Compile Inno Setup installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "Windows\installer.iss"

      # ---------------- LINUX INSTALLER ----------------
      - name: Prepare Linux installer
        shell: bash
        run: |
          mkdir -p LinuxOutput
          cp -r Linux/install.sh Linux/docker-compose.yml InstallerSource/nginx.conf LinuxOutput/
          chmod +x LinuxOutput/install.sh
          cd LinuxOutput
          zip -r ../installer-linux.zip .


      # ---------------- UPLOAD RELEASE ----------------
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Windows/Output/*.exe
            installer-linux.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
