name: Build Inno Setup Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Inno Setup
        run: |
          choco install innosetup --no-progress

      - name: Compile Inno Setup installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MedicalSoftInstaller
          path: Output\*.exe
